import {
  AccountBalance,
  Assessment,
  Assignment,
  CalendarMonth,
  Campaign,
  CheckCircle,
  Class,
  Dashboard,
  Description,
  DirectionsBus,
  ErrorOutline,
  FamilyRestroom,
  Hotel,
  LibraryBooks,
  LocalLibrary,
  Message,
  Notifications,
  People,
  Person,
  PersonAdd,
  School,
  Settings,
  SportsBasketball,
  TrendingUp,
  VerifiedUser,
} from '@mui/icons-material';
import type { DashboardIconKey } from '../../dashboards/dashboardConfigs/types';

export function getDashboardIcon(icon: DashboardIconKey) {
  const icons: Record<DashboardIconKey, JSX.Element> = {
    academic: <School />,
    admission: <PersonAdd />,
    alert: <ErrorOutline />,
    assignment: <Assignment />,
    attendance: <CheckCircle />,
    book: <LocalLibrary />,
    bus: <DirectionsBus />,
    calendar: <CalendarMonth />,
    certificate: <VerifiedUser />,
    class: <Class />,
    dashboard: <Dashboard />,
    document: <Description />,
    exam: <Assessment />,
    finance: <AccountBalance />,
    hostel: <Hotel />,
    library: <LibraryBooks />,
    message: <Message />,
    notification: <Notifications />,
    people: <People />,
    person: <Person />,
    school: <School />,
    settings: <Settings />,
    sports: <SportsBasketball />,
    trend: <TrendingUp />,
    user: <FamilyRestroom />,
  };

  return icons[icon] ?? <Dashboard />;
}
